name: "Request Reviewers by Teams"
description: "Automatically request reviewers on our PR"
inputs:
  teams:
    description: "Teams"
    required: true
  token:
    description: "GitHub Token"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
